Implemented Validator
therealansh/iiit_sonepat_app pull request #47
Opened 2021-06-07 08:46 UTC by VanshKela

Fixed Issue https://github.com/therealansh/iiit_sonepat_app/issues/39

2021-06-07 09:04 UTC, therealansh commented on lib/constants/validators.dart
>    Pattern pattern =
this regex needs to be changed according to the college email id to check wether the mail id is a valid college id or not.

2021-06-07 09:04 UTC, therealansh commented on lib/ui/Auth/Login_Page/Auth.dart
>                                    //[TODO] ADD VALIDATOR HERE
remove this comment if the task is done.

2021-06-07 10:06 UTC, VanshKela commented
Should i close this pull request and make another one?

2021-06-07 10:23 UTC, VanshKela commented
Changed the regex to "^[A-Za-z0-9._%+-]+@iiitsonepat.ac.in$"

2021-06-08 09:28 UTC, therealansh commented
@VanshKela try using this regex ```/^[A-Za-z]+\.[0-9]+(@iiitsonepat)\.(ac)\.(in)$/g``` try out this site https://regex101.com/ for creating regex.

2021-06-08 09:30 UTC, therealansh requested changes

2021-06-08 09:30 UTC, therealansh commented on lib/constants/validators.dart
> +      r'^[A-Za-z0-9._%+-]+@iiitsonepat.ac.in$';
Regex takes in any alphanumeric followed by iiitsonepat.ac.in so its a wrong regex

2021-06-08 11:45 UTC, VanshKela commented
I have set autoValdiateMode to always for both email and password and changed regex again.

2021-06-08 13:54 UTC, therealansh requested changes

2021-06-08 13:54 UTC, therealansh commented on lib/ui/Auth/Login_Page/Auth.dart
> +                                    ScaffoldMessenger.of(context)
Use Fluttertoast (already in the pubsec.yaml), it looks aesthetic as well as goes with the UI

2021-06-08 14:32 UTC, therealansh approved these changes

2021-06-08 14:33 UTC, therealansh commented
LGTM, Thanks @VanshKela for the PR.

2021-06-08 14:34 UTC, merged

2021-06-08 14:34 UTC, VanshKela commented
Finally done with this.